# S3 bucket for Face Liveness reference & audit images.
# Constraint (AWS): must be in the SAME account and SAME region as the
# Rekognition Face Liveness endpoint. Object keys are generated by Rekognition.

resource "aws_s3_bucket" "liveness" {
  bucket        = local.bucket_name
  force_destroy = var.force_destroy_bucket

  tags = {
    Project = var.project_name
    Purpose = "rekognition-face-liveness-audit-images"
  }
}

# Block all public access — biometric/audit data must never be public.
resource "aws_s3_bucket_public_access_block" "liveness" {
  bucket                  = aws_s3_bucket.liveness.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "liveness" {
  bucket = aws_s3_bucket.liveness.id
  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

# Encrypt at rest with SSE-S3 (SSE-KMS also supported; see README).
resource "aws_s3_bucket_server_side_encryption_configuration" "liveness" {
  bucket = aws_s3_bucket.liveness.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_versioning" "liveness" {
  bucket = aws_s3_bucket.liveness.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Enforce TLS-only access.
resource "aws_s3_bucket_policy" "liveness_tls" {
  bucket = aws_s3_bucket.liveness.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "DenyInsecureTransport"
        Effect    = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          aws_s3_bucket.liveness.arn,
          "${aws_s3_bucket.liveness.arn}/*"
        ]
        Condition = {
          Bool = { "aws:SecureTransport" = "false" }
        }
      }
    ]
  })
}

# Lifecycle: expire audit images after 90 days (compliance retention window —
# tune to your policy). Reference/audit images are only needed transiently.
resource "aws_s3_bucket_lifecycle_configuration" "liveness" {
  bucket = aws_s3_bucket.liveness.id
  rule {
    id     = "expire-audit-images"
    status = "Enabled"
    filter {
      prefix = "liveness-audit/"
    }
    expiration {
      days = 90
    }
    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}
